export default {

    // --- SYSTEM --- //
    SET_USERAGENT: 'SET_USERAGENT',
    SET_TITLE: 'SET_TITLE',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_ERROR: 'SET_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',
    SET_CONFIG: 'SET_CONFIG',
    SET_THEME: 'SET_THEME',
    SET_AUTH: 'SET_AUTH',

    // --- PRODUCTS --- //
    RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
    RECEIVE_TOTAL_PRODUCTS: 'RECEIVE_TOTAL_PRODUCTS',
    SET_LOADING_PRODUCTS: 'SET_LOADING_PRODUCTS'
}
